language: node_js
node_js:
  - "12"
script: "true"
deploy:
  repo: wenerme/wenerme.github.io
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: story
  on:
    branch: master
