language: node_js
node_js:
  - "12"
before_script:
  - echo building $$TRAVIS_BUILD_DIR
  - cd ..
  - git clone --depth 1 https://github.com/facebook/docusaurus
  - cd docusaurus
  - mv $TRAVIS_BUILD_DIR wener
  - git apply wener/site/docusaurus.patch
script:
  - yarn
  - NODE_ENV=production yarn workspace wener-website build
  # restore
  - mv wener ..
  # - cd ${TRAVIS_BUILD_DIR}
  # customized public material
  # - rsync -avrc /docusaurus/wener/site/public /docusaurus/wener/site/build

# deploy to github pages
deploy:
  fqdn: wener.me
  repo: wenerme/wenerme.github.io
  provider: pages
  github_token: $GITHUB_TOKEN
  # delete all the files created during the build, which will probably delete what you are trying to upload.
  skip_cleanup: true
  # git push --force
  keep_history: false
  # org page
  target_branch: master
  # from ~/wenerme/wener
  local_dir: site/build
  on:
    branch: master
