language: node_js
node_js:
  - "12"
before_script:
  - git clone --depth 1 -b wenerme https://github.com/wenerme/docusaurus
  # customized site settings
  - rsync -avrc site/ docusaurus/my/
  - ln -s . docusaurus/my/content
script:
  - cd docusaurus
  - yarn
  - yarn build:my
  # customized public material
  - rsync -avrc site/public/ docusaurus/my/build/

# deploy to github pages
deploy:
  fqdn: wener.me
  repo: wenerme/wenerme.github.io
  provider: pages
  github_token: $GITHUB_TOKEN
  # delete all the files created during the build, which will probably delete what you are trying to upload.
  skip_cleanup: true
  # git push --force
  keep_history: false
  # org page
  target_branch: master
  local_dir: docusaurus/my/build
  on:
    branch: master
