language: node_js
node_js:
  - "12"
before_script:
  - git clone --depth 1 -b wenerme https://github.com/wenerme/docusaurus
  # customized site settings
  - rsync -avrc site/ docusaurus/my/
  # symbol link will failed webpack
  #  - ln -s $PWD docusaurus/my/content
  - mkdir docusaurus/my/content
  - mv story docusaurus/my/content
  - mv tricks docusaurus/my/content
# symbol link will failed webpack
#  - ln -s $PWD docusaurus/my/content

script:
  - cd docusaurus
  - yarn
  - NODE_ENV=production yarn build:my
  - cd ${TRAVIS_BUILD_DIR}
  # customized public material
  - rsync -avrc site/public/ docusaurus/my/build/

# deploy to github pages
deploy:
  fqdn: wener.me
  repo: wenerme/wenerme.github.io
  provider: pages
  github_token: $GITHUB_TOKEN
  # delete all the files created during the build, which will probably delete what you are trying to upload.
  skip_cleanup: true
  # git push --force
  keep_history: false
  # org page
  target_branch: master
  local_dir: docusaurus/my/build
  on:
    branch: master
